# Generated by Django 5.0.6 on 2025-08-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_email_failed_customuser_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_failed',
            field=models.BooleanField(default=False, help_text='Indicates if verification email failed to send'),
        ),
        migrations.CreateModel(
            name='EmailResendAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('attempt_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_resend_attempts',
                'indexes': [models.Index(fields=['email', 'attempt_date'], name='email_resen_email_27525f_idx')],
            },
        ),
    ]
